# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'fenzhi' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fenzhi
	pod 'SVProgressHUD'
	pod 'SnapKit', '~> 3.0.2'
	pod 'SwiftyJSON'
	pod 'Kingfisher'
	pod 'MJRefresh'
	pod 'Alamofire', '~> 4.5'
	pod 'ObjectMapper', '~> 2.1' 
	pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
    pod 'UMengUShare/UI'
    pod 'UMengUShare/Social/ReducedWeChat'
    pod 'UMengUShare/Social/ReducedQQ'
    pod 'WechatOpenSDK'
    pod 'AliyunOSSiOS'
	pod 'GTSDK'

  target 'fenzhiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fenzhiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
